### ISSUE TITLE
Empty sam file

### ISSUE THREAD

**Issue by michoug** [saima-tithi/FastViromeExplorer#4]
Hi,
When running the test example, the `pseudoalignments.bam` is 1.6 Mb and the `FastViromeExplorer-reads-mapped-sorted.sam` file is empty. I think that it is due to the  samtools software whose options changed between version 1.5 and 1.8/1.9
Best
Greg

**Comment by saima-tithi** [comment]
Hi, 
Could you please check the kallisto version you are using? `pseudoalignments.bam` file is produced by kallisto version 0.44 and later. Here for developing FastViromeExplorer we used kallisto version 0.43.1. As in later versions of kallisto, the output format of pseudoalignments is different, our tool is not compatible with later versions of kallisto, please use Kallisto version 0.43.0 or 0.43.1.

**Comment by michoug** [comment]
Thanks, indeed it worked !

**Comment by sarahgraff** [comment]
I am having this issue even though I am using Kallisto 0.43.1 - was this updated for a newer version of Kallisto?
